### ISSUE TITLE
Filter by geographical displayed extent

### ISSUE THREAD

**Issue by alexvaut** [alexandrainst/alexandra-trackmap-panel#1]
Hi, 

first: very nice plugin !
second: is there a way to use the displayed extent in the query, something like that:

``SELECT time_index, latitude as lat, longitude as lon
FROM doc.table_name
WHERE $__timeFilter(time_index)
AND lat >= $minLat
AND lat <= $maxLat
AND lon >= $minLong
AND lon <= $maxLong
ORDER BY time_index

I have a DB with billions of locations so retrieving only what is viewed would make this plugin usable.

Thanks !

**Comment by alexvaut** [comment]
That is great, thank you very much, I will test it as soon as I can !

**Comment by Alkarex** [comment]
For reference: https://github.com/alexandrainst/alexandra-trackmap-panel/commit/5bb5276ac318d131ab582847bb634004208f4fa4
