### ISSUE TITLE
 it is not marked on the map with postgres

### ISSUE THREAD

**Issue by Crisesm** [alexandrainst/alexandra-trackmap-panel#10]
I don't think this is a mistake but I can't make it mark on the map

create the column in postgres as timestam 
![DeepinScreenshot_Seleccionar área_20191228224835](https://user-images.githubusercontent.com/40926691/71551343-48354180-29c4-11ea-907b-de329c01e51e.png)
![DeepinScreenshot_Seleccionar área_20191228224855](https://user-images.githubusercontent.com/40926691/71551346-4d928c00-29c4-11ea-82b8-e8e4b481b14e.png)

what am I doing wrong?

**Comment by Drazair** [comment]
Hey @Crisesm, sorry for the very late response. 

It doesn't look like you are doing anything wrong. Is it still not being marked on the map?

**Comment by victorUTF** [comment]
I have the same problem, I'm also using Postgres and the SQL was correct and I'm also using the same syntax as yours. 

Any news?

**Comment by Drazair** [comment]
Hey @victorUTF, have you set the "Format as" to "Table" instead of the default "Time series"?
If you have can you see the data from the query in the browsers console log?

**Comment by victorUTF** [comment]
The problem was probably the installation, uninstalling and installing again worked.
Anyway, thanks @Drazair

**Comment by Drazair** [comment]
Okay good to hear, I'll close the issue then
