### ISSUE TITLE
Plugin at risk of deprecation

### ISSUE THREAD

**Issue by sympatheticmoose** [alexandrainst/alexandra-trackmap-panel#116]
Hi @Alkarex @pesintta

Following up to https://github.com/alexandrainst/alexandra-trackmap-panel/issues/105#issuecomment-1845322336

Given the latest published version is still based on the legacy Angular framework, this plugin is now at risk of being [deprecated](https://grafana.com/legal/plugin-deprecation/) and removed from the [catalog](https://grafana.com/grafana/plugins).

Please advise if you have any plans to publish the new version or whether you would prefer to deprecate this plugin to discourage further adoption. I'll deprecate the plugin in 30 days unless I hear otherwise.

Thank you for your contributions to the Grafana ecosystem ❤️

**Comment by Alkarex** [comment]
Hello,
From my organisation, we do not have anybody would can support such a work at the moment.
But let's hear @pesintta in particular, who has done the most recent contributions.

**Comment by pesintta** [comment]
Since Grafana has recently moved to the direction of including built-in support for track map type features I think that we can let the plugin be deprecated.

**Comment by sympatheticmoose** [comment]
Thanks both
