### ISSUE TITLE
Data Point not plotting in the graph - InfluxCloud DB

### ISSUE THREAD

**Issue by vimalgupta** [alexandrainst/alexandra-trackmap-panel#12]
Hi,
I a trying this plug-in with grafana and using influx cloud DB database.

I am unable to see any data point s drawn. 

can you please guide me how can I use it with influx cloud DB.

below is my output of the query.
,result,table,_time,_value,_field
,_result,0,2020-02-18T07:27:58.853339466Z,17.4632916,lat
,_result,0,2020-02-18T07:27:58.853864976Z,17.4632916,lat
,_result,0,2020-02-18T07:28:58.017188544Z,17.4632916,lat
,_result,0,2020-02-18T07:28:58.017295643Z,17.4632916,lat

**Comment by ursweiss** [comment]
Hi,

I ran into the same problem and spent hours (literally...) to finally find out.

I use a single query like this:
`SELECT "time" AS "time_index", "latitude" AS "lat", "longitude" AS "lon" FROM "state" WHERE ("entity_id" = '<you entity_id>') AND $timeFilter GROUP BY time_index fill(null)`

**The most important thing is to set the "Format as" to "Table" and not "Time series", or it will never work.**

This hint should probably be added to the README, as many use Grafana with a TSDB.

**Comment by Drazair** [comment]
@vimalgupta, have your problem been fixed?

@ursweiss, I'll make it more clear in the readme

**Comment by viktak** [comment]
Hi,
I'm also having difficulties with this. Even editing is difficult, as

1. If I edit the old queries (that worked with Grafana 6.x) I get an error page, with no option to go back and edit further - I have to restart.

**Comment by Alkarex** [comment]
@viktak Is that with our [latest release 2.1.0](https://github.com/alexandrainst/alexandra-trackmap-panel/releases/tag/2.1.0) ?

**Comment by viktak** [comment]
@Alkarex

Thanks for asking. I just checked and I see version 1.2.5.... I just assumed that the latest one got pulled as I just upgraded Grafana too to 7.3.1. Using Docker.

Is the official one in the Grafana Plugin list still the old one? Should I install it directly from git?

**Comment by viktak** [comment]
@Alkarex And kudos to you for the super fast reply! 👍

**Comment by Alkarex** [comment]
Our branch 1.x is for Grafana 6, while our branch 2.x is for Grafana 7+.
Our new branch 2.x is currently under review https://github.com/grafana/grafana-plugin-repository/pull/766 (you can give it a 👍) so for now you have to pull our release manually.

**Comment by viktak** [comment]
Is this the correct link?
https://github.com/alexandrainst/alexandra-trackmap-panel/archive/2.1.0.zip

Your link gives me a version of 2.0.0 (although the title says 2.1.0)

I installed 2.1.0 and so far it doesn't show the error page as before, but I still have to figure out how to get my maps back :)

I expect to figure it out in a few minutes, and then I'll report back!

**Comment by Alkarex** [comment]
Yes, that is correct

**Comment by viktak** [comment]
Can't seem to make it work...
This is my query (stolen/adapted from @ursweiss ):
`SELECT "time" AS "time_index", "latitude" AS "lat", "longitude" AS "lon" FROM "autogen"."device_tracker.XXX_galaxya5" WHERE ("entity_id" = 'XXX_galaxya5') AND $timeFilter GROUP BY time_index fill(null)`
I set Format as Table.

when the query runs with Table visualization, it displays the timestamps and coordinates, although the coordinates only show the integer part. This is a sample row:
```
1604592858204 47 18
```

When I switch visualization to Track Map, I only see an empty map centered on Aarhus, Denmark (which is not even the "integer" coordinates).

**Comment by viktak** [comment]
I got it working, thank you for the help!
Here comes the proof:
![vtracker-sample-log-on-map](https://user-images.githubusercontent.com/12509879/98391572-b91aa080-204e-11eb-94ba-966dfa54d0b6.png)

I have noticed though, that now the map can center on the first or the last point (which is great), but I cannot make the map center/zoom on the "action". In the previous version, by default, it zoomed just enough to show all the points in the track. Is this option still available somewhere?

**Comment by viktak** [comment]
While we are at it:
The documentation says this:
`To add text tooltips to the markers, a text ordesc field should be added. If no tooltip exists in the data, latitude and longitude are displayed as the tooltip.`
I tried it, and I can display a number of things, but not the timestamp. After some research I seem to think that selecting the Time field in InfluxDB is not possible. Is there any workaround/trickery to make this possible? Having a timestamp, in my opinion, is probably the most common/useful "extra" in the tooltip.

**Comment by viktak** [comment]
Also, some kind of formatting would be essential: What I mean is, now I can display a number, say the speed, in the tooltip, but only as it is, a number. I would like to display it as xx km/h, rather than just XX.

Maybe I just haven't figured it out?

In Grafana I tried using transformations, but I couldn't get it to convert the speed value to string and then concatenate it with the unit.
Any ideas?

**Comment by j-or** [comment]
@viktak FYI I've just added zooming in on the "action" (i.e. setting the map to fit all the positions on load) with #37. Try it by enabling "Zoom map to fit data bounds".

**Comment by viktak** [comment]
@Alkarex Thank you for the update!
Where do I find that `Zoom map to fit data bounds` option? I just upgraded my plugin to 2.2.0, but I can't seem to find it...

**Comment by viktak** [comment]
@Alkarex  Never mind, I found it. I just didn't see it because another one was active.
Thanks  again it's a great plugin!!
