### ISSUE TITLE
More than one trace on the same map

### ISSUE THREAD

**Issue by jononi** [alexandrainst/alexandra-trackmap-panel#13]
I'm using InfluxDB to get the data. 
Adding one query like this:
`SELECT mean("latitude") AS "lat", mean("longitude") AS "lon" FROM "track_rp"."location" WHERE ("device" = 'device-1') AND $timeFilter GROUP BY time($__interval) fill(none)`
works fine. 
When I add a second query:
`SELECT mean("latitude") AS "lat", mean("longitude") AS "lon" FROM "track_rp"."location" WHERE ("device" = 'device-2') AND $timeFilter GROUP BY time($__interval) fill(none)`

I can't view both on the same map. If I disable one of them I get the other one displayed correctly.
Is there a way to have 2 (or more) traces displayed concurrently?

**Comment by Drazair** [comment]
Hey @jononi, there currently isn't a way to have multiple queries displayed on the map at the same time.

**Comment by viktak** [comment]
I would also like to have this feature in the future :)

**Comment by alchuk** [comment]
+1
And not only multiple tracks but also some annotations next to the last pont in track so that moving vehicles could distinct from each other

**Comment by bijwaard** [comment]
Enabling multiple paths would also enable drawing more static paths, such as walking trails, connections between smartgrid substations, etc. 
- Having both static and dynamic maps would enable showing deviations between them, e.g. deviation from the walking trail;-) 
- Having the smartgrid paths may enable me to show the actual power as intensity on the lines (connections) and/or points (substations).
