### ISSUE TITLE
How to use re-center as starting position

### ISSUE THREAD

**Issue by Alcarin** [alexandrainst/alexandra-trackmap-panel#16]
First of all this plugin is fantastic. I use Antpath to track ship route, I have a dashboard variable to switch between ship, and re-center function is working good, as I change ship the map is recentered correctly to show all route. But when I first load the dashboard, the map show me the configured starting position, but I can't know where the ship could be, so starting position is meaningless for me in this situation. As I click to refresh dashboard data, re-center is triggered and route is now centered in the map. Is it possible to automatically re-centering the map at first data load instead of using configured start position?

**Comment by Drazair** [comment]
Hey @Alcarin, It should be using the automatically re-centering if it's on instead of the start position. 
This seems to be a bug if the the data loads in before the map is done initializing.

**Comment by viktak** [comment]
Just wanted to confirm - the same thing happens for me too. Otherwise, it's a great plugin!

**Comment by CodeFunta** [comment]
Hey @Alcarin ,
JFYI: I've pushed several PRs including centering on first position.

**Comment by viktak** [comment]
@CodeFunta Awesome, thank you! Can't wait to see it live!

**Comment by alchuk** [comment]
You know, guys, there's always room for improvement. The automatic re-centering works as a charm. But it's not that convenient without automatic zoom on the track boundaries. I'm sure you can implement this feature (: Please

**Comment by Alkarex** [comment]
@alchuk Could you please try https://github.com/alexandrainst/alexandra-trackmap-panel/pull/37 ?
