### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by grootwitbaas** [alexandrainst/alexandra-trackmap-panel#22]
I tried to install and use this plugin, but sadly if i select it from the menu i get the following error. 
click on track map
![image](https://user-images.githubusercontent.com/664442/91989221-8db6c500-ed30-11ea-8ba9-31ce0837dc95.png)
then
![image](https://user-images.githubusercontent.com/664442/91988984-3dd7fe00-ed30-11ea-8217-50c460adfb59.png)

Grafana Version 7.1.5 (commit: 9893b8c53d, branch: HEAD)
TrackMap Version 1.2.5

**Comment by Alkarex** [comment]
See https://github.com/alexandrainst/alexandra-trackmap-panel/issues/18
New version in the pipeline :-)

**Comment by Alkarex** [comment]
@grootwitbaas Would you be able to test this release candidate? https://github.com/alexandrainst/alexandra-trackmap-panel/pull/24
