### ISSUE TITLE
Unexpected error when running 

### ISSUE THREAD

**Issue by martijnsanderse** [alexandrainst/alexandra-trackmap-panel#23]
I've tried running the panel from docker on both macOS and Raspbian, like this:

docker run -p 3000:3000 --name grafana -e "GF_INSTALL_PLUGINS=alexandra-trackmap-panel" grafana/grafana

This currently runs grafana 7.1.5.

In both OS-es the panel installs just fine (it's available in the visualisation tab) but when I select it I get the error below. I'm fairly new to Grafana, what can I do to troubleshoot / fix this?

Kind regards,
Martijn

An unexpected error happened
TypeError: undefined is not an object (evaluating 'this.events.emit')

    in t
    in x
    in Qr
    in div
    in div
    in t
    in t
    in div
    in Wa
    in div
    in div
    in uo
    in div
    in t
    in div
    in t
    in div
    in div
    in t
    in x
    in div
    in t
    in x
    in r
    in Unknown
    in t
    in Unknown
    in h
    in Unknown
    in Unknown
    in t
    in t
    in l

**Comment by martijnsanderse** [comment]
I'm sorry, I now see that this is a double (https://github.com/alexandrainst/alexandra-trackmap-panel/issues/18)

**Comment by Alkarex** [comment]
@martijnsanderse Would you be able to test this release candidate? https://github.com/alexandrainst/alexandra-trackmap-panel/pull/24
