### ISSUE TITLE
Tracking multiple items

### ISSUE THREAD

**Issue by OddmarDam** [alexandrainst/alexandra-trackmap-panel#3]
Hi.

Is it possible to track multiple items ?
I have 3 ships that I'm tracking, data is stored as:
Timestamp, Imo (ship identifier), Name, Lat, Lon

**Comment by Drazair** [comment]
Hey OddmarDam,

It is possible to track multiple items, it's just not recommended to use ant-path with multiple items, since it won't give a path for each items, but one path with all items coordinates.

To track multiple items you just have to query them from your database.
