### ISSUE TITLE
Intensity hard to get working with TestData DB

### ISSUE THREAD

**Issue by bijwaard** [alexandrainst/alexandra-trackmap-panel#31]
Dear developers,

The TrackMap plugin seems to work great for visualisation of location paths in grafana 7.2.0.

I have basic points working with simple test-data, but have some trouble seeing individual points (green in options) and their intensity, I hope you guide me in the right direction to get this working. I have entered two points with latitude and longitude as well as 2 intensity values. With the intensity metric disabled I see a line between the two points. When I enable the intensity metric, the map goes back to worldview without any line.
![image](https://user-images.githubusercontent.com/6523124/97804955-432fc700-1c53-11eb-884e-cd4b534ce42c.png)

I was also hoping to have the identity_id or name of separate points visible with the point or with a tooltip, is this possible? I tried using the identiy_id mentioned from the older [TrackLab 1.2.5 documentation](https://grafana.com/grafana/plugins/alexandra-trackmap-panel).

Kind regards,
Dennis

**Comment by KejaPower** [comment]
hello, 
I have the same issue, I can't get the heatmap working( all other representation are working well). Is there a format a range to be followed? 
I'm using InfluxDB and my query looks like this :
SELECT "longitude","latitude" , "rssi" as "intensity" from "Tracker"
Format as a table.
My RSSI values are negative.
Thanks
Kind regards,
Nicolas

**Comment by ZhongyuWang** [comment]
> Dear developers,
> 
> The TrackMap plugin seems to work great for visualisation of location paths in grafana 7.2.0.
> 
> I have basic points working with simple test-data, but have some trouble seeing individual points (green in options) and their intensity, I hope you guide me in the right direction to get this working. I have entered two points with latitude and longitude as well as 2 intensity values. With the intensity metric disabled I see a line between the two points. When I enable the intensity metric, the map goes back to worldview without any line.
> ![image](https://user-images.githubusercontent.com/6523124/97804955-432fc700-1c53-11eb-884e-cd4b534ce42c.png)
> 
> I was also hoping to have the identity_id or name of separate points visible with the point or with a tooltip, is this possible? I tried using the identiy_id mentioned from the older [TrackLab 1.2.5 documentation](https://grafana.com/grafana/plugins/alexandra-trackmap-panel).
> 
> Kind regards,
> Dennis

Hi,

Could you please try heatmap to see whether you could get the intensity visualized?

Here is an example I made:
![Capture](https://user-images.githubusercontent.com/15715503/98640347-5e24ca00-232a-11eb-8bd6-f9216fda46e0.PNG)

**Comment by ZhongyuWang** [comment]
> hello,
> I have the same issue, I can't get the heatmap working( all other representation are working well). Is there a format a range to be followed?
> I'm using InfluxDB and my query looks like this :
> SELECT "longitude","latitude" , "rssi" as "intensity" from "Tracker"
> Format as a table.
> My RSSI values are negative.
> Thanks
> Kind regards,
> Nicolas

Hi,

The intensity has to be positive. You might need a minus sign before your "rssi".

**Comment by KejaPower** [comment]
Hello,

Thanks, it works once I've modified my rssi to be positive.
Kind regards,
Nicolas

**Comment by bijwaard** [comment]
Hi ZhongyuWang,
I still don't get the intensity working with the TestData DB, is this because it needs to be a table or needs more than 2 values?
Also the points don't get visualized in the specified color, only the line between them.
Furthermore, it is unclear to me how to activate the heatmap, I don't see configuration items for that.
![image](https://user-images.githubusercontent.com/6523124/98652907-9c2ae980-233c-11eb-8452-fcc670c07dc8.png)

Kind regards,
Dennis

**Comment by j-or** [comment]
@bijwaard Are you sure this is our plugin? The options look very different. Are you maybe using this one? https://grafana.com/grafana/plugins/pr0ps-trackmap-panel

**Comment by bijwaard** [comment]
I used the following to install the plugin in grafana 7.3.1, re-install didn't have effect:

sudo grafana-cli plugins install pr0ps-trackmap-panel

Here is the visualisation part of the options
![image](https://user-images.githubusercontent.com/6523124/98656580-1eb5a800-2341-11eb-9740-d30991edf47f.png)

**Comment by j-or** [comment]
@bijwaard You are using a different plugin with a very similar name to ours. This site is _alexandra-trackmap-panel_ - you are using _pr0ps-trackmap-panel_. 

Feel free to try ours though. It has GPS-markers, paths and heatmap visualisations. The newest version working with Grafana 7 is still pending merge to the Grafana plugin repo https://github.com/grafana/grafana-plugin-repository/pull/766 but you can try the newest version from this repo until it is added.

**Comment by bijwaard** [comment]
Hi,
Thanks!
It is indeed very confusing that they have the same name, I'll try yours when it is merged with the plugin repo

Kind regards,
Dennis

**Comment by bijwaard** [comment]
I couldn't wait;-) And dived into yarn / nodeJS install.
This works great!!!

This trackmap is working, both with markers and with intensity.
![image](https://user-images.githubusercontent.com/6523124/98675201-36e5f100-235a-11eb-8ef4-b0ffcd6cd677.png)
![image](https://user-images.githubusercontent.com/6523124/98675532-aeb41b80-235a-11eb-8716-59c9cdcdd42d.png)
