### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by DmitrySidorow** [alexandrainst/alexandra-trackmap-panel#38]
Missing a dark theme (or satellite) like in the original world map plugin

![Screenshot_3](https://user-images.githubusercontent.com/43705385/99508551-c6605500-2995-11eb-8aae-e35e91598011.png)

**Comment by tpachmann** [comment]
Hi guys,

first of all thank you for the great plugin!

For my personal usecase, I wanted to use a dark/satellite style for the map - so I added a configuration option to set the URL for the map tiles that are loaded from the map. 

This allows you to use the Mapbox Static Tile API for example - but also other, publicly available tile servers can be used this way:

![map-tiles-config](https://user-images.githubusercontent.com/47070812/113518994-edf13c00-9589-11eb-8362-b773e6201903.png)


I think this feature could also be of interest for other users of the plugin (e.g. this issue), so I wanted to create pull request for my feature branch.
Sadly, I have no permission to push my branch - is there any chance you could help me with this (@Alkarex)?

Thanks in advance & best regards!
Tim

**Comment by Alkarex** [comment]
@tpachmann Thanks for reaching out, that looks good. Permissions should not be a problem if using the normal procedure: first fork the project (top right button in GitHub - it will then appear in https://github.com/tpachmann?tab=repositories ), then push your feature branch in your own repository, then send us a pull request, which we will test and merge. If you already have your local branch but only our own git remote, you can easily add your git remote with something like:

```sh
git remote add tpachmann https://github.com/tpachmann/alexandra-trackmap-panel.git
git fetch --all
git push tpachmann your-feature # adapt as needed
```
