### ISSUE TITLE
Handling clicks on the marker

### ISSUE THREAD

**Issue by DmitrySidorow** [alexandrainst/alexandra-trackmap-panel#39]
It would be great if you could switch to other dashboards when you click on the marker. With support for field variables in the url.

**Comment by bijwaard** [comment]
Having links per marker would indeed be very handy. You could have a look at the [flowcharting plugin](https://github.com/algenty/grafana-flowcharting) that has this working via mapping rules.

**Comment by DmitrySidorow** [comment]
great implementaion in https://github.com/panodata/grafana-map-panel

**Comment by bijwaard** [comment]
Wow, how many map panels are there? The grafana-map-panel looks a lot like the worldmap panel, or is it the same? I didn't get it to work with the testdata db.

**Comment by amotl** [comment]
Dear Dennis,

at first, I would like to salute @Drazair, @j-or, @CodeFunta and @Alkarex for their excellent work on the Alexandra Trackmap Panel.

> The grafana-map-panel looks a lot like the worldmap panel, or is it the same?

It is a fork of the original Worldmap Panel by @daniellee and contributors, but we tried to improve it on many ends by a) collecting further contributions from the community and b) adding some things from our own pen. Saying this, we still try to keep up with regular maintenance and have also been able to integrate further contributions there.

For a look back at history, you might want to refer to [1]. For a reasonably up-to-date summary, please enjoy reading [2].

> Wow, how many map panels are there?

At [3], we tried hard to outline many of the most valuable contributions from other forks of the original Worldmap Panel. Feel free to add more suggestions there.

> I didn't get it to work with the testdata db.

We will be happy to hear about more details what you exactly tried and where it is failing.

With kind regards,
Andreas.

[1] https://community.hiveeyes.org/t/developing-grafana-worldmap-ng/1824
[2] https://community.panodata.org/t/grafana-map-panel/121
[3] https://github.com/panodata/grafana-map-panel/issues/20

**Comment by bijwaard** [comment]
Dear Andreas,

In retrospect not so strange that the different map panels look alike, thanks for the history lesson and links;-)

I really like the marker visualisation that we can customize in the Alexandra fork, with hyperlinks on the markers they become even more valuable.

A further suggestion is to make some of the options (like visualisation type) changable via grafana template variables, so they can also be toggled in viewing role with selections (i.e. without edit mode).

Kind regards,
Dennis

**Comment by j-or** [comment]
@amotl Thanks, both for the kind words and for adding info. 
@bijwaard Just to clarify, alexandra-trackmap-panel (this repo) is not a fork but a different plugin built from scratch. So just to clear up any confusion (hopefully 😉 ), an overview of the various map plugins mentioned here and in other issues now looks something like this:

https://github.com/grafana/worldmap-panel: Original map plugin
https://github.com/panodata/grafana-map-panel: Fork of original worldmap-panel with added improvements
https://github.com/alexandrainst/alexandra-trackmap-panel: This repo, another map plugin (not a fork)
https://github.com/pR0Ps/grafana-trackmap-panel: Also a map plugin (not a fork)

**Comment by amotl** [comment]
Dear Jack,

thanks for clarifying. I haven't been aware that this might have confused people. Do you believe I should also make it more clear at https://github.com/panodata/grafana-map-panel/issues/20#issuecomment-573387329?

With kind regards,
Andreas.

**Comment by j-or** [comment]
The popup is now parsed as HTML, so adding a link there will work.
<img width="309" alt="link" src="https://user-images.githubusercontent.com/36296721/144993052-66db70aa-9030-47d9-b3a1-a04e59fa747c.png">
