### ISSUE TITLE
map dont show the points

### ISSUE THREAD

**Issue by fjacobsabalia** [alexandrainst/alexandra-trackmap-panel#4]
Hi! 

Im trying to use the plugin and make your example to use but it doesnt work the response its like this.

![image](https://user-images.githubusercontent.com/50323519/67005267-8370e580-f0e2-11e9-8d4a-7de460030792.png)

and my query is:

SELECT time, latitude as lat, longitude as lon
FROM doc.datasource
WHERE $__timeFilter(time)
ORDER BY time

where the datasource has the next structure 

zip | city | states | latitude | longitude | time | daylight
71937 | Cove | AR | 34.398483 | -94.39398 | 1571306316 | 1

im using cratedb and my model is 

create table datasource (
   zip text,
   city text,
   states text,
   latitude double precision,
   longitude double precision,
   time timestamp without time zone,
   daylight text
 );

**Comment by fjacobsabalia** [comment]
please delete this issue or use as example i only need to change from timeseries to table 
![image](https://user-images.githubusercontent.com/50323519/67006484-8b7e5480-f0e5-11e9-9bd7-89e31efc7897.png)

**Comment by Alkarex** [comment]
Thanks for the feedback 👍
