### ISSUE TITLE
Tracking position on map from other panels

### ISSUE THREAD

**Issue by xkilian** [alexandrainst/alexandra-trackmap-panel#43]
Use-case: Select a time frame like last 30 minutes
1 Panel with ant-path and markers.
1 Panel showing a metric as a graph
Select the shared crosshair option in Grafana global options for the panel.

Hover over the graph. 
Trackmap should highlight the marker for the given timestamp using the alternate colour(if markers are displayed). If ant-path is selected display a marker at the position of time timestamp that moves along the path as the hover is moved on the graph. Similar to props-trackmap. Very useful to correlate metrics to positions. While a tooltip on hover in trackmap is available in the plugin currently, the amount of data associated with each popup is limited to a single metric. The timestamp is also not shared to other graphs(shared crosshair grafana function) and is not as easy to use as hovering over an adjacent graph panel.

Great work with the plugin.

**Comment by bvilnis** [comment]
+1 on this.

I'm wanting to record dust levels from vehicles on dirt roads. While I can currently hover over the markers having `dust` set as `tooltip`, it would be much more user friendly to be able to hover over my dust level line graph and have the respective markers or path highlighted on the map. Or even better, the ability to change marker/line color based on parameters from another value (in my case a dust level reading).

I'm with @xkilian, great work on this! By far the best geospatial plugin!

**Comment by Alkarex** [comment]
We are a bit busy at the moment, but pull requests welcome!

**Comment by xkilian** [comment]
"The react solution for getting the cursor position is to subscribe to the eventbus in the
PanelProps with the DataHoveEvent."

Thanks to @leonardopivetta for finding this.

**Comment by 2Belette** [comment]
I got the exact same use case with map and some other metrics for running and would be so nice to correlate the metric with the position. Any if you found a working solution?

**Comment by xkilian** [comment]
Someone needs to step up and implement it in the current plugin. I am not a web developper, so I guess this is an open call for contributions!

**Comment by Alkarex** [comment]
> Someone needs to step up and implement it in the current plugin. I am not a web developper, so I guess this is an open call for contributions!

@xkilian We happily accept pull requests, so input welcome, but we do not have many resources at the moment to develop new features
