### ISSUE TITLE
Ant-Path is not chronologically connected

### ISSUE THREAD

**Issue by xkilian** [alexandrainst/alexandra-trackmap-panel#44]
The path jumps around when a vehicule is in proximity of its own path.
When the vehicule is on a linear or near linear path it looks ok.

![image](https://user-images.githubusercontent.com/1302719/106233962-b9e24f00-61c5-11eb-88db-5b85e30ccda6.png)

Am I missing a configuration item to get it to work properly?

**Comment by anirudh-ramesh** [comment]
@xkilian, could you check if your query is ordered by time asc/desc either? This behaviour has been observed when not ordered by time, and eliminating that could be one step towards reproducing this.

**Comment by xkilian** [comment]
This is data coming from a loki event stream which is converted to a table using a Grafana Transform. I have not see any indication that this data could sequence other than newest to oldest. I will look around in Grafana to see.

**Comment by anirudh-ramesh** [comment]
Yeah, I think it's worth a relook at Grafana because when I saw your screenshot, it pretty clearly looks to me like the ant path is an `ORDER BY longitude DESC` (or `ORDER BY latitude DESC` if the map is rotated by any means, or `ASC` in either if the ant path is moving up instead of down) or its equivalent in Loki.

**Comment by xkilian** [comment]
That sounds plausible. I have no clue how to get it re-ordered by time, so any suggestions are welcome.

**Comment by xkilian** [comment]
Ok, inspecting the data in the panel, shows that it is indeed ordered by latitude or longitude and not by time. I still have not figured out how to change it.. Suggestions welcome.
![image](https://user-images.githubusercontent.com/1302719/106314058-2f3a3800-6237-11eb-9033-1b7352f9cf0f.png)

**Comment by xkilian** [comment]
I think we can close this issue as it is unrelated to TrackMap. Thank you,

**Comment by xkilian** [comment]
The origin of this issue has been acknowledged in Loki by the maintainers. If using using Loki and Labels to Fields Grafana feature the output cannot be used in the TrackMap plugin as the data is not strictly ordered by time. AS of writing this will not work in Grafana 7.3.5 and Loki 2.1.
