### ISSUE TITLE
Track Map does not appear in Grafana 7.4.2

### ISSUE THREAD

**Issue by wstarzak** [alexandrainst/alexandra-trackmap-panel#50]
As the tittle says, can we get the compatibility with the newest version?

**Comment by wstarzak** [comment]
indeed, i have used 2.2.1 and then tried also master. I got back to Grafana 7.0.4 and it works.

**Comment by mmichelli** [comment]
I had the same issue, module.js is not loading. 
A hack is to renamed it to be "module".

**Comment by ZhongyuWang** [comment]
@wstarzak Could you please elaborate your issue a bit more. I have deployed an empty Grafana 7.4.2 docker image with the Track map v2.2.1 successfully. Could you please guide me how to reproduce your issue.

**Comment by ZhongyuWang** [comment]
Close for now and feel free to post more information.
