### ISSUE TITLE
"Zoom map to fit data bounds" option not zooming

### ISSUE THREAD

**Issue by ElBalsero** [alexandrainst/alexandra-trackmap-panel#59]
Hi,
I have the last version of the plugin (just downloaded) running on Grafana 7.5.5. 
When I center in the first point, it zooms there according to the zoom parameters. Same for the last point.
However, when using the option "Zoom map to fit data bounds", the map remains zoomed over a place in Denmark. 
I would expect the map to zoom around the area where there are points. Isn't that what should happen or it is not working as expected?
Regards,
Daniel

**Comment by ElBalsero** [comment]
Is there anyone maintaining this plugin?

**Comment by Alkarex** [comment]
> Is there anyone maintaining this plugin?

Yes, but only with few resources, and with a focus on our most important needs. So pull requests welcome and additional contributors and maintainers as well :-)

**Comment by ElBalsero** [comment]
> > Is there anyone maintaining this plugin?
> 
> Yes, but only with few resources, and with a focus on our most important needs. So pull requests welcome and additional contributors and maintainers as well :-)

Thanks for the answer, @Alkarex. I understand the situation. I wish I had the ability to help.

Could you at least tell me if I am using the option correctly and "Zoom map to fit data bounds is supposed to zoom the map just around the antpath area?

**Comment by dmak** [comment]
Subscribing to the issue as I experience the same with plugin latest master snapshot on Grafana 8.x.

> Could you at least tell me if I am using the option correctly and "Zoom map to fit data bounds is supposed to zoom the map just around the antpath area?

My answer is not authoritative, but I believe yes: the map should be centered and zoomed in/out so that the path fits the view boundaries.
