### ISSUE TITLE
Is it possible to have more than one "popup/text/desc" field? 

### ISSUE THREAD

**Issue by pbhetwal** [alexandrainst/alexandra-trackmap-panel#60]
I am trying to display more than one popup per lat, long point.

**Comment by j-or** [comment]
You can't add two "popups" or two "tooltips" to one marker. You can either add all your information inside the same popup/tooltip, or have one of each with different content in the two. So you can show one thing on mouseover and another on click.
<img width="317" alt="popup_tooltip" src="https://user-images.githubusercontent.com/36296721/144996424-158d4c6d-0239-4e49-b3e8-e52fb6c09fa3.png">
