### ISSUE TITLE
Re-centre map

### ISSUE THREAD

**Issue by sptrakesh** [alexandrainst/alexandra-trackmap-panel#9]
I did a very simple implementation where I re-centre the map after data points have been retrieved.  It is probably best to make this a configuration option, but for my case this is good enough.

https://github.com/alexandrainst/alexandra-trackmap-panel/compare/master...sptrakesh:master

**Comment by Drazair** [comment]
The re-center of the map is now implemented in version 1.2.4. 
https://github.com/alexandrainst/alexandra-trackmap-panel/commit/be44cbdbd345ddfdd8bc09dead0b5fd63c7ac813
